# ! DO NOT set latest here USE custom hash !
image: registry.gitlab.com/satoshilabs/trezor/trezor-suite/base:5d4ee34202486b6bf06218850f98590b772013ed

cache:
    untracked: true
    policy: pull
    key: node_modules-across-the-monorepo-universe
    paths:
        - .yarn
        # modules
        - node_modules/
        - packages/blockchain-link/node_modules/
        - packages/components/node_modules/
        - packages/components-v2/node_modules/
        - packages/components-storybook/node_modules/
        - packages/components-storybook-v2/node_modules/
        - packages/connect-explorer/node_modules/
        - packages/rollout/node_modules/
        - packages/suite/node_modules/
        - packages/suite-web/node_modules/
        - packages/suite-desktop/node_modules/
        - packages/suite-native/node_modules/
        - packages/suite-storage/node_modules/
        - packages/translations-manager/node_modules/
        - packages/integration-tests/node_modules/
          # libs
        - packages/components/lib
        - packages/components-v2/lib
        - packages/blockchain-link/lib
        - packages/rollout/lib
        - packages/suite-storage/lib
        - packages/translations-manager/lib

variables:
    DEV_SERVER_URL: 'https://suite.corp.sldev.cz'
    PACKAGE_PATH_COMPONENTS: packages/components-storybook
    PACKAGE_PATH_SUITE_DESKTOP: packages/suite-desktop
    PACKAGE_PATH_SUITE_NATIVE: packages/suite-native
    PACKAGE_PATH_SUITE_WEB: packages/suite-web

stages:
    - setup environment
    - lint, types and unit tests
    - build
    - deploy to dev servers
    - integration testing
    - misc

include:
    - ci/environment.yml
    - ci/install-and-build.yml
    - ci/packages/components-storybook.yml
    - ci/packages/components-storybook-v2.yml
    - ci/packages/suite.yml
    - ci/packages/suite-web.yml
    - ci/packages/suite-desktop.yml
    - ci/packages/suite-native.yml

lint:
    stage: lint, types and unit tests
    dependencies:
        - install and build
    script:
        - lerna run lint

type check:
    stage: lint, types and unit tests
    dependencies:
        - install and build
    script:
        - lerna run type-check

unit tests:
    stage: lint, types and unit tests
    dependencies:
        - install and build
    script:
        - lerna run test:unit -- --passWithNoTests
