# ! DO NOT set latest here USE custom hash !
image: registry.gitlab.com/satoshilabs/trezor/trezor-suite/base:c51f080789c0f0c9683a96090e335831cde283b4

variables:
    DEV_SERVER_URL: 'https://suite.corp.sldev.cz'
    PACKAGE_PATH_COMPONENTS: packages/components-storybook
    PACKAGE_PATH_SUITE_DESKTOP: packages/suite-desktop
    PACKAGE_PATH_SUITE_NATIVE: packages/suite-native
    PACKAGE_PATH_SUITE_WEB: packages/suite-web

cache:
    key: node_modules-suite
    paths:
        - node_modules
        - packages/blockchain-link/node_modules
        - packages/components/node_modules
        - packages/components-v2/node_modules
        - packages/components-storybook/node_modules
        - packages/components-storybook-v2/node_modules
        - packages/connect-explorer/node_modules
        - packages/rollout/node_modules
        - packages/suite/node_modules
        - packages/suite-web/node_modules
        - packages/suite-desktop/node_modules
        - packages/suite-native/node_modules
        - packages/suite-storage/node_modules
        - packages/translations-manager/node_modules
        - packages/integration-tests/node_modules

stages:
    - setup environment
    - lint, types and unit tests
    - build
    - deploy to dev servers
    - integration testing
    - misc

include:
    - ci/environment.yml
    - ci/install-and-build.yml
    - ci/packages/components-storybook.yml
    - ci/packages/components-storybook-v2.yml
    - ci/packages/suite.yml
    - ci/packages/suite-web.yml
    - ci/packages/suite-desktop.yml
    - ci/packages/suite-native.yml

before_script:
    - yarn install

lint:
    stage: lint, types and unit tests
    dependencies:
        - install and build
    script:
        - lerna run lint

type check:
    stage: lint, types and unit tests
    dependencies:
        - install and build
    script:
        - lerna run type-check

unit tests:
    stage: lint, types and unit tests
    dependencies:
        - install and build
    script:
        - lerna run test:unit -- --passWithNoTests
