# ! DO NOT set latest here USE custom hash !
image: registry.gitlab.com/satoshilabs/trezor/trezor-suite/base:latest

variables:
    DEV_SERVER_URL: 'https://suite.corp.sldev.cz'
    PACKAGE_PATH_COMPONENTS: packages/components-storybook
    PACKAGE_PATH_SUITE_DESKTOP: packages/suite-desktop
    PACKAGE_PATH_SUITE_NATIVE: packages/suite-native
    PACKAGE_PATH_SUITE_WEB: packages/suite-web

stages:
    - setup environment
    - lint, types and unit tests
    - build
    - deploy to dev servers
    - integration testing
    - misc

include:
    - ci/environment.yml
    - ci/install-and-build.yml
    - ci/packages/components-storybook.yml
    - ci/packages/components-storybook-v2.yml
    - ci/packages/suite.yml
    - ci/packages/suite-web.yml
    - ci/packages/suite-desktop.yml
    - ci/packages/suite-native.yml

before_script:
    - yarn

lint:
    cache:
        policy: pull
    stage: lint, types and unit tests
    dependencies:
        - install and build
    script:
        - lerna run lint

type check:
    cache:
        policy: pull
    stage: lint, types and unit tests
    dependencies:
        - install and build
    script:
        - lerna run type-check

unit tests:
    cache:
        policy: pull
    stage: lint, types and unit tests
    dependencies:
        - install and build
    script:
        - lerna run test:unit -- --passWithNoTests
